force-app/main/default/objects/ApexTruth1__c/ApexTruth1__c.object-meta.xml
<CustomObject>
    <description>See README</description>
    <label>Apex Truth 1</label>
    <nameField>
        <label>Apex Truth 1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Truth 1's</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApexTruth1__c/fields/IsRerun__c.field-meta.xml
<CustomField>
    <fullName>IsRerun__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rerun</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LogEntry__c/LogEntry__c.object-meta.xml
<CustomObject>
    <description>Messages used to validate expectations</description>
    <label>Log Entry</label>
    <nameField>
        <displayFormat>LE-{00000000}</displayFormat>
        <label>Log Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogEntry__c/fields/ApexTruth1__c.field-meta.xml
<CustomField>
    <fullName>ApexTruth1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apex Truth 1</label>
    <referenceTo>ApexTruth1__c</referenceTo>
    <relationshipLabel>Log Entries</relationshipLabel>
    <relationshipName>LogEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApexTruth1Test.cls
@isTest
private class ApexTruth1Test {

    @isTest
    private static void insertRecord() {

        // Given
        List<ApexTruth1__c> givenTruths = getApexTruth1s();

        System.assertEquals(0, givenTruths.size());

        List<LogEntry__c> givenEntries = getLogEntries(null);

        System.assertEquals(0, givenEntries.size());

        // When
        Test.startTest();

        insert new ApexTruth1__c(Name = 'test');

        // Then
        Test.stopTest();

        List<ApexTruth1__c> thenTruths = getApexTruth1s();

        System.assertEquals(1, thenTruths.size());

        System.assertEquals('TEST', thenTruths[0].Name);

        System.assertEquals(false, thenTruths[0].IsRerun__c);

        List<LogEntry__c> thenOrphanEntries = getLogEntries(null);

        System.assertEquals(1, thenOrphanEntries.size());

        System.assertEquals(
                'before insert: 1', thenOrphanEntries[0].Message__c);

        List<LogEntry__c> thenTruthEntries = getLogEntries(thenTruths[0].Id);

        System.assertEquals(5, thenTruthEntries.size());
    }

    private static List<ApexTruth1__c> getApexTruth1s() {
        return [
            SELECT
                IsRerun__c,
                Name,
                Id
            FROM ApexTruth1__c
        ];
    }

    private static List<LogEntry__c> getLogEntries(Id apexTruth1Id) {
        return [
            SELECT
                Message__c,
                Id
            FROM LogEntry__c
            WHERE ApexTruth1__c = :apexTruth1Id
        ];
    }
}